
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar 22 2024 12:20:59 +07 (Mar 22 2024 05:20:59 UTC)

// Verification Directory fv/labLSI 

module labLSI(reset, clk, flick, led);
  input reset, clk, flick;
  output [15:0] led;
  wire reset, clk, flick;
  wire [15:0] led;
  wire [4:0] counter;
  wire [15:0] curr_state;
  wire ascending, descending, kickBackFlag, n_0, n_1, n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177;
  assign kickBackFlag = 1'b0;
  assign descending = 1'b0;
  assign curr_state[2] = 1'b0;
  assign curr_state[1] = 1'b0;
  assign curr_state[0] = 1'b0;
  assign counter[4] = 1'b0;
  assign counter[3] = 1'b0;
  assign counter[2] = 1'b0;
  assign counter[1] = 1'b0;
  assign counter[0] = 1'b0;
  assign led[0] = 1'b0;
  assign led[1] = 1'b0;
  assign led[2] = 1'b0;
  assign led[3] = 1'b0;
  assign led[4] = 1'b0;
  assign led[5] = 1'b0;
  assign led[6] = 1'b0;
  assign led[7] = 1'b0;
  assign led[8] = 1'b0;
  assign led[9] = 1'b0;
  assign led[10] = 1'b0;
  assign led[11] = 1'b0;
  assign led[12] = 1'b0;
  assign led[13] = 1'b0;
  assign led[14] = 1'b0;
  assign led[15] = 1'b0;
  DFFHQX4 ascending_reg(.CK (clk), .D (n_25), .Q (ascending));
  DFFHQX4 ascending_reg563(.CK (clk), .D (n_173), .Q (ascending));
  DFFHQX1 \counter_reg[0]553 (.CK (clk), .D (n_174), .Q (counter[0]));
  DFFHQX1 \counter_reg[1]554 (.CK (clk), .D (n_168), .Q (counter[1]));
  DFFHQX1 \counter_reg[2]555 (.CK (clk), .D (n_169), .Q (counter[2]));
  DFFHQX1 \counter_reg[3]556 (.CK (clk), .D (n_172), .Q (counter[3]));
  DFFHQX1 \counter_reg[4]557 (.CK (clk), .D (n_152), .Q (counter[4]));
  DFFHQX1 \curr_state_reg[0]521 (.CK (clk), .D (n_171), .Q
       (curr_state[0]));
  DFFHQX1 \curr_state_reg[1]522 (.CK (clk), .D (n_123), .Q
       (curr_state[1]));
  DFFHQX1 \curr_state_reg[2]523 (.CK (clk), .D (n_145), .Q
       (curr_state[2]));
  DFFHQX1 descending_reg565(.CK (clk), .D (n_176), .Q (descending));
  EDFFHQX1 kickBackFlag_reg567(.CK (clk), .D (n_43), .E (n_147), .Q
       (kickBackFlag));
  DFFHQX1 \led_reg[0]492 (.CK (clk), .D (n_148), .Q (led[0]));
  DFFHQX1 \led_reg[1]493 (.CK (clk), .D (n_159), .Q (led[1]));
  DFFHQX1 \led_reg[2]494 (.CK (clk), .D (n_166), .Q (led[2]));
  DFFHQX1 \led_reg[3]495 (.CK (clk), .D (n_158), .Q (led[3]));
  DFFHQX1 \led_reg[4]496 (.CK (clk), .D (n_161), .Q (led[4]));
  DFFHQX1 \led_reg[5]497 (.CK (clk), .D (n_149), .Q (led[5]));
  DFFHQX1 \led_reg[6]498 (.CK (clk), .D (n_157), .Q (led[6]));
  DFFHQX1 \led_reg[7]499 (.CK (clk), .D (n_155), .Q (led[7]));
  DFFHQX1 \led_reg[8]500 (.CK (clk), .D (n_167), .Q (led[8]));
  DFFHQX1 \led_reg[9]501 (.CK (clk), .D (n_156), .Q (led[9]));
  DFFHQX1 \led_reg[10]502 (.CK (clk), .D (n_160), .Q (led[10]));
  DFFHQX1 \led_reg[11]503 (.CK (clk), .D (n_154), .Q (led[11]));
  DFFHQX1 \led_reg[12]504 (.CK (clk), .D (n_162), .Q (led[12]));
  DFFHQX1 \led_reg[13]505 (.CK (clk), .D (n_165), .Q (led[13]));
  DFFHQX1 \led_reg[14]506 (.CK (clk), .D (n_153), .Q (led[14]));
  DFFHQX1 \led_reg[15]507 (.CK (clk), .D (n_163), .Q (led[15]));
  NAND2XL g11139__2398(.A (n_111), .B (n_175), .Y (n_176));
  AOI221X1 g11144__5107(.A0 (n_144), .A1 (descending), .B0 (n_94), .B1
       (n_72), .C0 (n_107), .Y (n_175));
  OAI211X1 g11145__6260(.A0 (n_90), .A1 (n_1), .B0 (n_151), .C0
       (n_150), .Y (n_174));
  OAI21X4 g11146__4319(.A0 (n_141), .A1 (n_177), .B0 (n_170), .Y
       (n_173));
  OAI222XL g11147__8428(.A0 (n_143), .A1 (counter[3]), .B0 (n_105), .B1
       (n_3), .C0 (n_48), .C1 (n_21), .Y (n_172));
  OAI21X4 g11163__5526(.A0 (n_32), .A1 (n_50), .B0 (n_164), .Y (n_171));
  AOI221X1 g11164__6783(.A0 (n_126), .A1 (descending), .B0 (n_31), .B1
       (n_3), .C0 (n_112), .Y (n_170));
  OAI211X1 g11165__3680(.A0 (n_56), .A1 (n_33), .B0 (n_146), .C0
       (n_106), .Y (n_169));
  OAI221X1 g11166__1617(.A0 (n_120), .A1 (n_11), .B0 (n_124), .B1
       (counter[1]), .C0 (n_119), .Y (n_168));
  OAI211X1 g11170__2802(.A0 (n_68), .A1 (n_71), .B0 (n_132), .C0
       (n_70), .Y (n_167));
  OAI211X1 g11171__1705(.A0 (n_61), .A1 (n_71), .B0 (n_134), .C0
       (n_70), .Y (n_166));
  OAI211X1 g11172__5122(.A0 (n_18), .A1 (n_54), .B0 (n_127), .C0
       (n_70), .Y (n_165));
  AOI221X1 g11173__8246(.A0 (n_108), .A1 (curr_state[0]), .B0 (n_24),
       .B1 (n_29), .C0 (n_99), .Y (n_164));
  OAI211X1 g11174__7098(.A0 (n_71), .A1 (n_74), .B0 (n_139), .C0
       (n_70), .Y (n_163));
  OAI211X1 g11175__6131(.A0 (n_87), .A1 (n_54), .B0 (n_128), .C0
       (n_70), .Y (n_162));
  OAI211X1 g11176__1881(.A0 (n_87), .A1 (n_51), .B0 (n_136), .C0
       (n_70), .Y (n_161));
  OAI211X1 g11177__5115(.A0 (n_13), .A1 (n_71), .B0 (n_130), .C0
       (n_70), .Y (n_160));
  OAI211X1 g11178__7482(.A0 (n_81), .A1 (n_51), .B0 (n_135), .C0
       (n_70), .Y (n_159));
  OAI211X1 g11179__4733(.A0 (n_81), .A1 (n_55), .B0 (n_133), .C0
       (n_70), .Y (n_158));
  OAI211X1 g11180__6161(.A0 (n_87), .A1 (n_55), .B0 (n_138), .C0
       (n_70), .Y (n_157));
  OAI211X1 g11181__9315(.A0 (n_81), .A1 (n_54), .B0 (n_125), .C0
       (n_70), .Y (n_156));
  OAI211X1 g11182__9945(.A0 (n_18), .A1 (n_55), .B0 (n_140), .C0
       (n_70), .Y (n_155));
  OAI211X1 g11183__2883(.A0 (n_81), .A1 (n_52), .B0 (n_129), .C0
       (n_70), .Y (n_154));
  OAI211X1 g11184__2346(.A0 (n_87), .A1 (n_52), .B0 (n_142), .C0
       (n_70), .Y (n_153));
  OAI221X1 g11185__1666(.A0 (n_17), .A1 (n_86), .B0 (n_100), .B1
       (n_74), .C0 (n_137), .Y (n_152));
  AOI221X1 g11186__7410(.A0 (n_93), .A1 (n_21), .B0 (n_12), .B1
       (n_110), .C0 (n_121), .Y (n_151));
  AOI32X1 g11187__6417(.A0 (n_72), .A1 (n_52), .A2 (n_21), .B0 (n_122),
       .B1 (n_9), .Y (n_150));
  OAI211X1 g11188__5477(.A0 (n_62), .A1 (n_71), .B0 (n_117), .C0
       (n_70), .Y (n_149));
  OAI211X1 g11189__2398(.A0 (n_63), .A1 (n_71), .B0 (n_113), .C0
       (n_70), .Y (n_148));
  NAND3BXL g11191__5107(.AN (n_112), .B (n_111), .C (n_102), .Y
       (n_147));
  AOI32X1 g11192__6260(.A0 (n_104), .A1 (n_56), .A2 (n_27), .B0 (n_67),
       .B1 (n_34), .Y (n_146));
  OAI2BB1X1 g11193__4319(.A0N (n_49), .A1N (curr_state[2]), .B0
       (n_131), .Y (n_145));
  OR4X1 g11194__8428(.A (n_65), .B (n_101), .C (n_51), .D (n_0), .Y
       (n_144));
  AOI32X1 g11195__5526(.A0 (n_91), .A1 (n_56), .A2 (n_27), .B0 (n_89),
       .B1 (counter[1]), .Y (n_143));
  OAI2BB1X1 g11196__6783(.A0N (n_45), .A1N (n_97), .B0 (led[14]), .Y
       (n_142));
  NOR3BXL g11197__3680(.AN (n_95), .B (counter[4]), .C (n_65), .Y
       (n_141));
  OAI2BB1X1 g11198__1617(.A0N (n_47), .A1N (n_19), .B0 (led[7]), .Y
       (n_140));
  OAI2BB1X1 g11199__2802(.A0N (n_47), .A1N (n_97), .B0 (led[15]), .Y
       (n_139));
  OAI2BB1X1 g11200__1705(.A0N (n_45), .A1N (n_19), .B0 (led[6]), .Y
       (n_138));
  OAI2BB1X1 g11201__5122(.A0N (n_105), .A1N (n_41), .B0 (counter[4]),
       .Y (n_137));
  OAI2BB1X1 g11202__8246(.A0N (n_45), .A1N (n_20), .B0 (led[4]), .Y
       (n_136));
  OAI21XL g11203__7098(.A0 (n_46), .A1 (n_98), .B0 (led[1]), .Y
       (n_135));
  OAI21XL g11204__6131(.A0 (n_57), .A1 (n_96), .B0 (led[2]), .Y
       (n_134));
  OAI21XL g11205__1881(.A0 (n_46), .A1 (n_96), .B0 (led[3]), .Y
       (n_133));
  OAI21XL g11206__5115(.A0 (n_57), .A1 (n_103), .B0 (led[8]), .Y
       (n_132));
  NAND4XL g11207__7482(.A (n_2), .B (n_85), .C (n_29), .D (reset), .Y
       (n_131));
  NAND2XL g11208__4733(.A (n_118), .B (led[10]), .Y (n_130));
  NAND2XL g11209__6161(.A (n_116), .B (led[11]), .Y (n_129));
  NAND2XL g11210__9315(.A (n_115), .B (led[12]), .Y (n_128));
  NAND2XL g11211__9945(.A (n_114), .B (led[13]), .Y (n_127));
  AOI31X1 g11212__2883(.A0 (n_77), .A1 (n_75), .A2 (n_73), .B0 (n_63),
       .Y (n_126));
  OAI21XL g11213__2346(.A0 (n_46), .A1 (n_103), .B0 (led[9]), .Y
       (n_125));
  AOI21XL g11214__1666(.A0 (n_92), .A1 (counter[0]), .B0 (n_15), .Y
       (n_124));
  OAI21XL g11215__7410(.A0 (n_17), .A1 (n_73), .B0 (n_109), .Y (n_123));
  OAI222XL g11216__6417(.A0 (n_86), .A1 (counter[3]), .B0 (n_73), .B1
       (n_3), .C0 (n_44), .C1 (n_40), .Y (n_122));
  OAI222XL g11217__5477(.A0 (n_80), .A1 (n_33), .B0 (n_60), .B1 (n_21),
       .C0 (n_88), .C1 (counter[0]), .Y (n_121));
  AOI22XL g11218__2398(.A0 (n_104), .A1 (n_21), .B0 (n_10), .B1 (n_8),
       .Y (n_120));
  OA21X1 g11219__5107(.A0 (n_78), .A1 (n_4), .B0 (n_90), .Y (n_119));
  NAND2BXL g11220__6260(.AN (n_57), .B (n_97), .Y (n_118));
  OAI21XL g11221__4319(.A0 (n_84), .A1 (n_82), .B0 (led[5]), .Y
       (n_117));
  NAND2BXL g11222__8428(.AN (n_46), .B (n_97), .Y (n_116));
  NAND2BXL g11223__5526(.AN (n_103), .B (n_45), .Y (n_115));
  NAND2BXL g11224__6783(.AN (n_103), .B (n_47), .Y (n_114));
  OAI21XL g11225__3680(.A0 (n_79), .A1 (n_82), .B0 (led[0]), .Y
       (n_113));
  MXI2XL g11226__1617(.A (n_83), .B (n_39), .S0 (n_0), .Y (n_110));
  OAI21XL g11227__2802(.A0 (n_17), .A1 (n_75), .B0 (curr_state[1]), .Y
       (n_109));
  OAI21XL g11228__1705(.A0 (n_85), .A1 (curr_state[2]), .B0 (reset), .Y
       (n_108));
  OAI22XL g11229__5122(.A0 (n_62), .A1 (n_88), .B0 (n_83), .B1 (n_38),
       .Y (n_107));
  AOI22XL g11230__8246(.A0 (n_15), .A1 (counter[1]), .B0 (n_44), .B1
       (counter[2]), .Y (n_106));
  NOR3XL g11231__7098(.A (n_28), .B (n_86), .C (n_62), .Y (n_112));
  OAI211X1 g11232__6131(.A0 (n_12), .A1 (n_64), .B0 (n_72), .C0
       (flick), .Y (n_111));
  NAND3BXL g11233__1881(.AN (n_53), .B (n_76), .C (n_85), .Y (n_102));
  OA21X1 g11234__5115(.A0 (n_76), .A1 (n_23), .B0 (counter[0]), .Y
       (n_101));
  OA21X1 g11235__7482(.A0 (n_14), .A1 (curr_state[0]), .B0 (n_88), .Y
       (n_100));
  NOR3XL g11236__4733(.A (n_66), .B (n_62), .C (kickBackFlag), .Y
       (n_99));
  AOI221X1 g11237__6161(.A0 (n_11), .A1 (n_21), .B0 (n_7), .B1
       (counter[0]), .C0 (n_65), .Y (n_105));
  OAI21XL g11238__9315(.A0 (n_44), .A1 (n_35), .B0 (n_86), .Y (n_104));
  OAI2BB1X1 g11239__9945(.A0N (n_54), .A1N (n_26), .B0 (n_16), .Y
       (n_103));
  AOI222X1 g11242__2883(.A0 (n_42), .A1 (n_21), .B0 (n_39), .B1 (n_3),
       .C0 (n_59), .C1 (counter[3]), .Y (n_95));
  MXI2XL g11243__2346(.A (n_13), .B (n_74), .S0 (curr_state[0]), .Y
       (n_94));
  OAI32X1 g11244__1666(.A0 (n_58), .A1 (flick), .A2 (n_1), .B0 (n_66),
       .B1 (n_3), .Y (n_93));
  OAI22XL g11245__7410(.A0 (n_71), .A1 (n_35), .B0 (n_14), .B1 (flick),
       .Y (n_92));
  OAI2BB1X1 g11246__6417(.A0N (n_10), .A1N (counter[4]), .B0 (n_86), .Y
       (n_91));
  OAI2BB1X1 g11247__5477(.A0N (n_51), .A1N (n_26), .B0 (n_16), .Y
       (n_98));
  AOI21X1 g11248__2398(.A0 (n_52), .A1 (n_26), .B0 (n_82), .Y (n_97));
  OAI2BB1X1 g11249__5107(.A0N (n_55), .A1N (n_26), .B0 (n_16), .Y
       (n_96));
  NOR2XL g11252__6260(.A (n_12), .B (n_6), .Y (n_84));
  NAND2BXL g11253__4319(.AN (n_74), .B (n_29), .Y (n_90));
  NOR2BX1 g11254__8428(.AN (n_34), .B (n_71), .Y (n_89));
  NAND2BXL g11255__5526(.AN (n_73), .B (n_0), .Y (n_88));
  NAND2BXL g11256__6783(.AN (n_71), .B (n_8), .Y (n_87));
  OR2X1 g11257__3680(.A (n_76), .B (n_53), .Y (n_86));
  NOR2XL g11258__1617(.A (n_63), .B (n_28), .Y (n_85));
  AOI21XL g11261__2802(.A0 (n_10), .A1 (descending), .B0 (n_72), .Y
       (n_80));
  AND2X1 g11262__1705(.A (n_63), .B (n_26), .Y (n_79));
  AOI221X1 g11263__5122(.A0 (n_28), .A1 (n_21), .B0 (counter[0]), .B1
       (n_1), .C0 (n_44), .Y (n_78));
  OR3X1 g11264__8246(.A (n_53), .B (n_2), .C (curr_state[0]), .Y
       (n_77));
  AOI21XL g11265__7098(.A0 (n_29), .A1 (kickBackFlag), .B0 (n_69), .Y
       (n_83));
  OAI221X1 g11266__6131(.A0 (n_6), .A1 (descending), .B0 (n_5), .B1
       (n_23), .C0 (reset), .Y (n_82));
  NAND2BXL g11267__1881(.AN (n_71), .B (n_37), .Y (n_81));
  ADDHX1 g11269__5115(.A (n_2), .B (n_22), .CO (n_69), .S (n_76));
  NAND2BXL g11270__7482(.AN (n_54), .B (n_27), .Y (n_68));
  NAND2XL g11271__4733(.A (n_31), .B (n_48), .Y (n_67));
  NAND2BXL g11272__6161(.AN (n_58), .B (n_2), .Y (n_75));
  NAND2BXL g11273__9315(.AN (n_52), .B (n_34), .Y (n_74));
  NAND2BXL g11274__9945(.AN (n_58), .B (n_23), .Y (n_73));
  NOR2XL g11275__2883(.A (n_53), .B (n_1), .Y (n_72));
  NAND2XL g11276__2346(.A (n_0), .B (n_10), .Y (n_71));
  OR2X1 g11277__1666(.A (n_49), .B (n_5), .Y (n_70));
  NAND2BXL g11280__7410(.AN (n_55), .B (n_27), .Y (n_61));
  OA21X1 g11281__6417(.A0 (descending), .A1 (n_0), .B0 (n_10), .Y
       (n_60));
  OAI211X1 g11282__5477(.A0 (curr_state[0]), .A1 (n_21), .B0
       (counter[1]), .C0 (curr_state[1]), .Y (n_59));
  OR2X1 g11283__2398(.A (n_53), .B (n_28), .Y (n_66));
  NAND3BXL g11284__5107(.AN (n_37), .B (n_33), .C (n_10), .Y (n_65));
  NOR2BX1 g11285__6260(.AN (n_27), .B (n_52), .Y (n_64));
  NAND2BXL g11286__4319(.AN (n_51), .B (n_27), .Y (n_63));
  NAND2BXL g11287__8428(.AN (n_51), .B (n_34), .Y (n_62));
  NAND2X8 g11290__5526(.A (n_6), .B (reset), .Y (n_50));
  NAND2XL g11291__6783(.A (n_36), .B (curr_state[0]), .Y (n_58));
  NOR2XL g11292__3680(.A (n_6), .B (n_27), .Y (n_57));
  NOR2XL g11293__1617(.A (n_28), .B (counter[1]), .Y (n_56));
  NAND2XL g11294__2802(.A (counter[1]), .B (n_35), .Y (n_55));
  NAND2XL g11295__1705(.A (n_4), .B (n_30), .Y (n_54));
  NAND2XL g11296__5122(.A (n_36), .B (curr_state[1]), .Y (n_53));
  NAND2XL g11297__8246(.A (counter[1]), .B (n_30), .Y (n_52));
  NAND2XL g11298__7098(.A (n_4), .B (n_35), .Y (n_51));
  NOR3XL g11300__6131(.A (n_23), .B (curr_state[2]), .C (n_1), .Y
       (n_43));
  OAI21XL g11301__1881(.A0 (n_22), .A1 (flick), .B0 (counter[3]), .Y
       (n_42));
  XNOR2X1 g11302__5115(.A (counter[3]), .B (counter[0]), .Y (n_41));
  AOI21XL g11303__7482(.A0 (n_3), .A1 (counter[1]), .B0 (counter[4]),
       .Y (n_40));
  NAND3BXL g11304__4733(.AN (n_22), .B (n_23), .C (reset), .Y (n_49));
  NAND2XL g11305__6161(.A (n_29), .B (n_30), .Y (n_48));
  NAND2BXL g11306__9315(.AN (n_34), .B (n_26), .Y (n_47));
  NOR2XL g11307__9945(.A (n_6), .B (n_37), .Y (n_46));
  NAND2XL g11308__2883(.A (n_33), .B (n_26), .Y (n_45));
  NAND2XL g11309__2346(.A (n_36), .B (n_26), .Y (n_44));
  NOR2X4 g11312__1666(.A (curr_state[2]), .B (flick), .Y (n_32));
  NOR2XL g11313__7410(.A (n_23), .B (flick), .Y (n_39));
  NAND2XL g11314__6417(.A (descending), .B (n_21), .Y (n_38));
  NOR2XL g11315__5477(.A (counter[2]), .B (n_21), .Y (n_37));
  AND2X1 g11316__2398(.A (n_5), .B (reset), .Y (n_36));
  NOR2XL g11317__5107(.A (counter[4]), .B (counter[3]), .Y (n_35));
  AND2X1 g11318__6260(.A (counter[0]), .B (counter[2]), .Y (n_34));
  NAND2XL g11319__4319(.A (counter[2]), .B (n_21), .Y (n_33));
  NAND2X2 g11322__8428(.A (reset), .B (n_177), .Y (n_25));
  NAND2XL g11323__5526(.A (n_5), .B (n_2), .Y (n_24));
  NOR2XL g11324__6783(.A (n_4), .B (n_1), .Y (n_31));
  NOR2XL g11325__3680(.A (counter[4]), .B (n_3), .Y (n_30));
  NOR2XL g11326__1617(.A (n_23), .B (n_22), .Y (n_29));
  NAND2XL g11327__2802(.A (n_1), .B (descending), .Y (n_28));
  NOR2XL g11328__1705(.A (counter[0]), .B (counter[2]), .Y (n_27));
  NAND2XL g11329__5122(.A (n_22), .B (n_23), .Y (n_26));
  CLKINVX4 g11334(.A (curr_state[1]), .Y (n_23));
  CLKINVX4 g11335(.A (curr_state[0]), .Y (n_22));
  INVX6 g11337(.A (counter[0]), .Y (n_21));
  INVX1 g11341(.A (n_72), .Y (n_14));
  INVX1 g11343(.A (n_85), .Y (n_17));
  INVX1 g11345(.A (n_64), .Y (n_13));
  INVX1 g11347(.A (n_82), .Y (n_16));
  INVX1 g11349(.A (n_81), .Y (n_15));
  INVX1 g11351(.A (n_98), .Y (n_20));
  INVX1 g11353(.A (n_96), .Y (n_19));
  INVX1 g11355(.A (n_89), .Y (n_18));
  INVX1 g11357(.A (n_44), .Y (n_10));
  INVX1 g11359(.A (n_62), .Y (n_12));
  INVX1 g11361(.A (n_56), .Y (n_11));
  INVX1 g11363(.A (n_38), .Y (n_9));
  INVX1 g11365(.A (n_33), .Y (n_8));
  INVX1 g11367(.A (n_31), .Y (n_7));
  INVX1 g11369(.A (n_26), .Y (n_6));
  INVX1 fopt11371(.A (n_1), .Y (n_0));
  INVX1 g11377(.A (counter[3]), .Y (n_3));
  INVX1 g11379(.A (curr_state[2]), .Y (n_5));
  INVX1 g11381(.A (kickBackFlag), .Y (n_2));
  INVX1 g11383(.A (counter[1]), .Y (n_4));
  CLKBUFX2 fopt11385(.A (n_177), .Y (n_1));
  CLKINVX12 g11403(.A (ascending), .Y (n_177));
endmodule

